kind: pipeline
name : LLVM Toolchain Compiler
version: rev1.5_template
platform:
  arch: amd64
  os: linux
steps:
 - name: LLVM-tc Compilation
  image: brock5555/recovery
   environment:
     TG_TOKEN:
       from_secret: TELEGRAM_BOT_TOKEN
     TG_CHAT_ID:
       from_secret: CHAT
     GH_USERNAME:
       from_secret: USERNAME
     GH_EMAIL:
       from_secret: EMAIL
     GH_TOKEN:
       from_secret: API_TOKEN_GITHUB
   commands:
     - bash llvm-tc_build.sh
